// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu3g5Bzzx7b64pTCXA2kO0pG9LJF18tU4',
    appId: '1:518528464182:web:35ae777bc9548c0b09ef97',
    messagingSenderId: '518528464182',
    projectId: 'sp1derboiz-music-app',
    authDomain: 'sp1derboiz-music-app.firebaseapp.com',
    storageBucket: 'sp1derboiz-music-app.firebasestorage.app',
    measurementId: 'G-9B0SYG3EV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4F8PwhbOHtnoE2WopsRQrLRSqSAj8PNc',
    appId: '1:518528464182:android:72aaefd099e054fb09ef97',
    messagingSenderId: '518528464182',
    projectId: 'sp1derboiz-music-app',
    storageBucket: 'sp1derboiz-music-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6EujZW6yvKUfrWlb7Hrc_zsRup4YYI24',
    appId: '1:518528464182:ios:e0af961b8893c84309ef97',
    messagingSenderId: '518528464182',
    projectId: 'sp1derboiz-music-app',
    storageBucket: 'sp1derboiz-music-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6EujZW6yvKUfrWlb7Hrc_zsRup4YYI24',
    appId: '1:518528464182:ios:e0af961b8893c84309ef97',
    messagingSenderId: '518528464182',
    projectId: 'sp1derboiz-music-app',
    storageBucket: 'sp1derboiz-music-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu3g5Bzzx7b64pTCXA2kO0pG9LJF18tU4',
    appId: '1:518528464182:web:8afb961bae86c58109ef97',
    messagingSenderId: '518528464182',
    projectId: 'sp1derboiz-music-app',
    authDomain: 'sp1derboiz-music-app.firebaseapp.com',
    storageBucket: 'sp1derboiz-music-app.firebasestorage.app',
    measurementId: 'G-9CYXDC6T76',
  );
}
